# Generated by Django 3.0.4 on 2021-02-25 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210206_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
