# Generated by Django 3.0.4 on 2021-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201214_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryproduct',
            name='desc',
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoryproduct',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='subcategoryproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
