# Generated by Django 3.0.4 on 2021-03-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_book',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
