# Generated by Django 3.0.4 on 2021-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210319_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_book',
            name='product',
            field=models.IntegerField(),
        ),
    ]
