# Generated by Django 3.0.4 on 2021-03-28 03:04

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210319_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='product_name',
            field=models.CharField(default=2, max_length=100, verbose_name=shop.models.Product),
            preserve_default=False,
        ),
    ]
