# Generated by Django 3.0.4 on 2021-03-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_book_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_book',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
