# Generated by Django 3.0.4 on 2021-04-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210327_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
