# Generated by Django 3.0.4 on 2021-06-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210504_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_book',
            name='price',
            field=models.FloatField(),
        ),
    ]
