# Generated by Django 3.0.4 on 2021-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210602_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
